export const car = [
  {
    src: "/car/accentdark.png",
    alt: "Accent",
    id: 'car1',
    sim: 'abc',
    petrol: 700,
    oil: 'Good',
    history: 'sd',
    status: 'Ready',
    under: 'Osman',
    km: 25875,
    width: 165,
    licence: 'valid',
    penalty: 'clear'
  },
  {
      src: "/car/accentgray.png",
      alt: "Accent",
      id: 'car2',
      sim: 'abc',
      petrol: 700,
      oil: 'Good',
      history: 'sd',
      status: 'Ready',
      under: 'Osman',
      km: 25875,
      width: 165,
      licence: 'valid',
      penalty: 'clear'
  },
  {
      src: "/car/accentwhite.png",
      alt: "Accent",
      id: 'car3',
      sim: 'abc',
      petrol: 700,
      oil: 'Good',
      history: 'sd',
      status: 'Ready',
      under: 'Osman',
      km: 25875,
      width: 140,
      licence: 'valid',
      penalty: 'clear'
  },
  {
      src: "/car/accentwhite.png",
      alt: "Accent",
      id: 'car4',
      sim: 'abc',
      petrol: 700,
      oil: 'Good',
      history: 'sd',
      status: 'Ready',
      under: 'Osman',
      km: 25875,
      width: 140,
      licence: 'valid',
      penalty: 'clear'
  },
  {
      src: "/car/sunny.png",
      alt: "Sunny",
      id: 'car5',
      sim: 'abc',
      petrol: 700,
      oil: 'Good',
      history: 'sd',
      status: 'Ready',
      under: 'Osman',
      km: 25875,
      width: 140,
      licence: 'valid',
      penalty: 'clear'
  },
  {
      src: "/car/sunny.png",
      alt: "Sunny",
      id: 'car6',
      sim: 'abc',
      petrol: 700,
      oil: 'Good',
      history: 'sd',
      status: 'Ready',
      under: 'Osman',
      km: 25875,
      width: 140,
      licence: 'valid',
      penalty: 'clear'
  },
  {
      src: "/car/sunny.png",
      alt: "Sunny",
      id: 'car7',
      sim: 'abc',
      petrol: 700,
      oil: 'Good',
      history: 'sd',
      status: 'Ready',
      under: 'Osman',
      km: 25875,
      width: 140,
      licence: 'valid',
      penalty: 'clear'
  },
  {
      src: "/car/creans.png",
      alt: "Creans",
      id: 'car8',
      sim: 'abc',
      petrol: 700,
      oil: 'Good',
      history: 'sd',
      status: 'Ready',
      under: 'Osman',
      km: 25875,
      width: 140,
      licence: 'valid',
      penalty: 'clear'
  },
  {
      src: "/car/tiida.png",
      alt: "Tiida",
      id: 'car9',
      sim: 'abc',
      petrol: 700,
      oil: 'Good',
      history: 'sd',
      status: 'Ready',
      under: 'Osman',
      km: 25875,
      width: 140,
      licence: 'valid',
      penalty: 'clear'
  },
  {
      src: "/car/tiida.png",
      alt: "Tiida",
      id: 'car10',
      sim: 'abc',
      petrol: 700,
      oil: 'Good',
      history: 'sd',
      status: 'Ready',
      under: 'Osman',
      km: 25875,
      width: 140,
      licence: 'valid',
      penalty: 'clear'
  },
  {
      src: "/car/tiida.png",
      alt: "Tiida",
      id: 'car11',
      sim: 'abc',
      petrol: 700,
      oil: 'Good',
      history: 'sd',
      status: 'Ready',
      under: 'Osman',
      km: 25875,
      width: 140,
      licence: 'valid',
      penalty: 'clear'
  },
  {
      src: "/car/isuzu.png",
      alt: "Isuzu",
      id: 'car12',
      sim: 'abc',
      petrol: 700,
      oil: 'Good',
      history: 'sd',
      status: 'Ready',
      under: 'Osman',
      km: 25875,
      width: 140,
      licence: 'valid',
      penalty: 'clear'
  },
]

export const docs = [
    { icon: 'ph:engine-thin', label: 'Status' },
    
    { icon: 'ph:gas-can-thin', label: 'Oil' },
    { icon: 'ph:gas-pump-thin', label: 'Petrol' },
    { icon: 'ph:sim-card-thin', label: 'SIM' },
    { icon: 'ph:camera-thin', label: 'Penalty' },
    { icon: 'arcticons:permissionsmanager', label: 'Licence' },
    { icon: 'ph:arrow-counter-clockwise-thin', label: 'History' },
    { icon: 'ph:ruler-thin', label: 'KM' },
    
    
  ]